INSERT INTO flights(origin, destination, departure, seats) VALUES('Tallinn','Helsinki','2025-04-02 15:42:54.067892455', 10);
INSERT INTO flights(origin, destination, departure, seats) VALUES('Tallinn','Helsinki','2025-04-02 15:42:54.067892455', 15);
INSERT INTO flights(origin, destination, departure, seats) VALUES('Tallinn','Stockholm','2025-04-02 15:42:54.067892455', 15);
INSERT INTO flights(origin, destination, departure, seats) VALUES('Tallinn','Stockholm','2025-04-02 15:42:54.067892455', 9);

INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,1,1,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,1,2,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,1,3,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,1,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,2,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,2,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,2,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,2,4,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,3,1,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,3,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,3,3,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,3,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,4,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,4,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,4,3,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,4,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,5,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,5,2,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,5,3,'t');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (1,5,4,'t');

INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,1,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,1,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,1,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,1,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,2,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,2,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,2,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,2,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,3,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,3,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,3,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,3,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,4,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,4,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,4,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,4,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,5,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,5,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,5,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (2,5,4,'f');

INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,1,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,1,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,1,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,1,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,2,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,2,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,2,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,2,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,3,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,3,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,3,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,3,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,4,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,4,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,4,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,4,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,5,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,5,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,5,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (3,5,4,'f');

INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,1,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,1,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,1,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,1,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,2,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,2,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,2,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,2,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,3,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,3,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,3,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,3,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,4,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,4,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,4,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,4,4,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,5,1,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,5,2,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,5,3,'f');
INSERT INTO seats(flightid,seaty,seatx,taken) VALUES (4,5,4,'f');